### ISSUE TITLE
Readme should specify VS >= 15.3.3

### ISSUE THREAD

**Issue by ckapilla** [DanWahlin/Angular-ASPNET-Core-CustomersService#1]
Without VS 15.3.3 the build fails and numerous incompatibility errors are given. No indication that VS is the culprit. For reasons I don't understand these errors also occur when trying to build in VS Code. Updating VS corrects everything in both environments.

**Comment by DanWahlin** [comment]
Thanks - I'll add that to the readme. I just hit that yesterday actually on another machine & the update resolved the problem as well.
