### ISSUE TITLE
Ignore this issue. followed instructions and worked. getting errors building on VS2017 15.5.3 

### ISSUE THREAD

**Issue by gurnamb** [DanWahlin/Angular-ASPNET-Core-CustomersService#3]
TS2307	Build:Cannot find module '@angular/core'.	Angular_ASPNETCore_CustomersService	F:\TEMP\angular-aspnetcore-restful-services\Angular-ASPNET-Core-CustomersService-master\Angular-ASPNET-Core-CustomersService\wwwroot\app\shared\pipes\capitalize.pipe.ts
Error	TS2304	(TS) Cannot find name 'require'.	Angular-ASPNET-Core-CustomersService (tsconfig project)	F:\TEMP\angular-aspnetcore-restful-services\Angular-ASPNET-Core-CustomersService-master\Angular-ASPNET-Core-CustomersService\config\polyfills.ts	3	Active
Error	TS2304	(TS) Cannot find name 'process'.	Angular-ASPNET-Core-CustomersService (tsconfig project)	F:\TEMP\angular-aspnetcore-restful-services\Angular-ASPNET-Core-CustomersService-master\Angular-ASPNET-Core-CustomersService\config\polyfills.ts	5	Active
Error	TS2339	(TS) Property 'stackTraceLimit' does not exist on type 'ErrorConstructor'.	Angular-ASPNET-Core-CustomersService (tsconfig project)	F:\TEMP\angular-aspnetcore-restful-services\Angular-ASPNET-Core-CustomersService-master\Angular-ASPNET-Core-CustomersService\config\polyfills.ts	9	Active
Error	TS2304	(TS) Cannot find name 'require'.	Angular-ASPNET-Core-CustomersService (tsconfig project)	F:\TEMP\angular-aspnetcore-restful-services\Angular-ASPNET-Core-CustomersService-master\Angular-ASPNET-Core-CustomersService\config\polyfills.ts	10	Active

**Comment by gurnamb** [comment]
[buildErrors_Gurnam.txt](https://github.com/DanWahlin/Angular-ASPNET-Core-CustomersService/files/1734901/buildErrors_Gurnam.txt)

**Comment by DanWahlin** [comment]
You got it working? The title makes it sounds like you did but let me know.

**Comment by gurnamb** [comment]
Yes. I just didn’t read your instructions on installing.

Once I did this then it worked fine:

Running the Application Locally on Windows
1.       Open the .sln file in Visual Studio
2.       Install Gulp: npm install gulp -g
3.       Run npm install to install app dependencies (make sure to run this in the folder where the package.json file lives)
4.       Run the following Gulp task to copy required Angular modules into the wwwroot folder:
gulp copy:libs
5.       Build and run the application (F5)
6.       Browse to http://localhost:5000<http://localhost:5000/>


Thank You,
Gurnam

**Comment by DanWahlin** [comment]
Glad you got it going.
