### ISSUE TITLE
Cannot run solution

### ISSUE THREAD

**Issue by asubitz** [DanWahlin/Angular-ASPNET-Core-CustomersService#4]
I cloned the repo onto local machine and did a dotnet install, dotnet build and dotnet run, but it seems to be missing some js libraries..

<img width="1440" alt="screen shot 2018-02-25 at 16 25 31" src="https://user-images.githubusercontent.com/12642325/36642497-b1e43a24-1a48-11e8-942c-b4388f7072da.png">

**Comment by DanWahlin** [comment]
Make sure you complete all of the steps listed in the readme file. Based on the error it looks like you didn't run the Gulp step.

**Comment by asubitz** [comment]
Yes, followed the steps in the readme file for mac and now it works.

Thank you! :)
