### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by shayaneumar** [DanWahlin/Angular-ASPNET-Core-CustomersService#5]
I am getting an error while building the project, what could be the reason?
![image](https://user-images.githubusercontent.com/3850812/39122826-a360c1f0-4713-11e8-8a04-b515a211d091.png)

**Comment by DanWahlin** [comment]
Make sure you ran all of the steps in the readme (don't skip any of them). I haven't seen that specific error but it sounds like something is missing that would be handled by the setup steps.

**Comment by DanWahlin** [comment]
Closing since it's been quite awhile since hearing back. If you are still having a problem please open up a new issue.
