### ISSUE TITLE
No gulpfile found while issuing the gulp copy:libs command

### ISSUE THREAD

**Issue by dheeraj-thedev** [DanWahlin/Angular-ASPNET-Core-CustomersService#6]
While issuing command it says no gulp file found.

![issue](https://user-images.githubusercontent.com/32265439/59102762-b80dad00-894a-11e9-854c-a5355a5f7600.png)

Thanks

**Comment by DanWahlin** [comment]
You have to run the command from the folder where the gulp file exists. Looks like you're too high in the folder structure.

This is an older project. I'd recommend using the project located at the following URL instead:

https://github.com/DanWahlin/AngularCLI-ASPNET-Core-CustomersService
